/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AppShoppingRouteImport } from './routes/_app.shopping'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppRecipesRouteImport } from './routes/_app.recipes'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppPantryRouteImport } from './routes/_app.pantry'
import { Route as AppNutritionRouteImport } from './routes/_app.nutrition'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBadgesRouteImport } from './routes/_app.badges'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppRecipesNewRouteImport } from './routes/_app.recipes.new'
import { Route as AppRecipesIdRouteImport } from './routes/_app.recipes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShoppingRoute = AppShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBadgesRoute = AppBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRecipesRoute,
} as any)
const AppRecipesIdRoute = AppRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai': typeof AppAiRoute
  '/badges': typeof AppBadgesRoute
  '/dashboard': typeof AppDashboardRoute
  '/discover': typeof AppDiscoverRoute
  '/notifications': typeof AppNotificationsRoute
  '/nutrition': typeof AppNutritionRoute
  '/pantry': typeof AppPantryRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/recipes': typeof AppRecipesRouteWithChildren
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/shopping': typeof AppShoppingRoute
  '/shared/$token': typeof SharedTokenRoute
  '/recipes/$id': typeof AppRecipesIdRoute
  '/recipes/new': typeof AppRecipesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai': typeof AppAiRoute
  '/badges': typeof AppBadgesRoute
  '/dashboard': typeof AppDashboardRoute
  '/discover': typeof AppDiscoverRoute
  '/notifications': typeof AppNotificationsRoute
  '/nutrition': typeof AppNutritionRoute
  '/pantry': typeof AppPantryRoute
  '/plan': typeof AppPlanRoute
  '/profile': typeof AppProfileRoute
  '/recipes': typeof AppRecipesRouteWithChildren
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/shopping': typeof AppShoppingRoute
  '/shared/$token': typeof SharedTokenRoute
  '/recipes/$id': typeof AppRecipesIdRoute
  '/recipes/new': typeof AppRecipesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/badges': typeof AppBadgesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/pantry': typeof AppPantryRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recipes': typeof AppRecipesRouteWithChildren
  '/_app/saved': typeof AppSavedRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shopping': typeof AppShoppingRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_app/recipes/$id': typeof AppRecipesIdRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai'
    | '/badges'
    | '/dashboard'
    | '/discover'
    | '/notifications'
    | '/nutrition'
    | '/pantry'
    | '/plan'
    | '/profile'
    | '/recipes'
    | '/saved'
    | '/settings'
    | '/shopping'
    | '/shared/$token'
    | '/recipes/$id'
    | '/recipes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai'
    | '/badges'
    | '/dashboard'
    | '/discover'
    | '/notifications'
    | '/nutrition'
    | '/pantry'
    | '/plan'
    | '/profile'
    | '/recipes'
    | '/saved'
    | '/settings'
    | '/shopping'
    | '/shared/$token'
    | '/recipes/$id'
    | '/recipes/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/ai'
    | '/_app/badges'
    | '/_app/dashboard'
    | '/_app/discover'
    | '/_app/notifications'
    | '/_app/nutrition'
    | '/_app/pantry'
    | '/_app/plan'
    | '/_app/profile'
    | '/_app/recipes'
    | '/_app/saved'
    | '/_app/settings'
    | '/_app/shopping'
    | '/shared/$token'
    | '/_app/recipes/$id'
    | '/_app/recipes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/shopping': {
      id: '/_app/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AppShoppingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry': {
      id: '/_app/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/badges': {
      id: '/_app/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AppBadgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRecipesRoute
    }
    '/_app/recipes/$id': {
      id: '/_app/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AppRecipesIdRouteImport
      parentRoute: typeof AppRecipesRoute
    }
  }
}

interface AppRecipesRouteChildren {
  AppRecipesIdRoute: typeof AppRecipesIdRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
}

const AppRecipesRouteChildren: AppRecipesRouteChildren = {
  AppRecipesIdRoute: AppRecipesIdRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
}

const AppRecipesRouteWithChildren = AppRecipesRoute._addFileChildren(
  AppRecipesRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppBadgesRoute: typeof AppBadgesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPantryRoute: typeof AppPantryRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecipesRoute: typeof AppRecipesRouteWithChildren
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShoppingRoute: typeof AppShoppingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppBadgesRoute: AppBadgesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPantryRoute: AppPantryRoute,
  AppPlanRoute: AppPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecipesRoute: AppRecipesRouteWithChildren,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShoppingRoute: AppShoppingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
